name: Build Varius OS 15 GSI

on:
  workflow_dispatch:
    inputs:
      android_version:
        description: 'Android Version'
        required: true
        default: '15'
        type: choice
        options:
        - 15
      gsi_variant:
        description: 'GSI Variant'
        required: true
        default: 'tdgsi_arm64_ab'
        type: choice
        options:
        - tdgsi_arm64_ab
        - tdgsi_arm64_a
        - tdgsi_arm64_ab_vndklite
      include_gapps:
        description: 'Include Core GApps? Play Store'
        required: true
        default: 'yes'
        type: choice
        options:
        - yes  # Core GApps
        - no   # Vanilla

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build GSI
      uses: yshalsager/aosp_gsi_builder@main
      with:
        os: 'AOSP'
        android_version: ${{ github.event.inputs.android_version }}
        variant: ${{ github.event.inputs.gsi_variant }}
        gapps: ${{ github.event.inputs.include_gapps }}
        root: 'ksu'  # KernelSU, ganti 'magisk' kalo mau Magisk
        
    - name: Upload GSI
      uses: actions/upload-artifact@v4
      with:
        name: Varius-OS-15-${{ github.event.inputs.include_gapps }}-${{ github.run_number }}
        path: release/
